# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
       disable_release: true
       extra_plugin_runners: 'git clone --branch MOODLE_405_STABLE-catalyst https://github.com/catalyst/moodle-tool_lifecycle.git $GITHUB_WORKSPACE/moodle/admin/tool/lifecycle'
